# Generated by Django 4.1.3 on 2022-11-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('predictions', models.CharField(max_length=255)),
            ],
        ),
    ]
